### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by phh** [swissspidy/wptalents#13]
Hi there :)

Is there a reason that the theme of wptalents.com is not here on github? :)

**Comment by swissspidy** [comment]
Good question!

It is on GitHub, but currently set to private. No idea why though, there's nothing magical about it.

When I finally get time to work on the site again and making it compatible with the latest WordPress version, I will definitely open it up.

**Comment by phh** [comment]
Sounds good. Thanks :)

**Comment by phh** [comment]
Or I'll maybe leave it open for now.

**Comment by swissspidy** [comment]
Screw it, I don't have time for this at the moment anyway, so I just made it public: https://github.com/swissspidy/talented

Feel free to dig through it. As you can see it's quite outdated :)

**Comment by phh** [comment]
Awesome thank you! I just want to research more how people are structuring their functionality in plugins and how it integrates with the theme.

Thanks :)
